"""Add editor_id to Video with constraint name

Revision ID: 2344cb22888f
Revises: f003ffe880d1
Create Date: 2025-04-24 17:49:24.986354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2344cb22888f'
down_revision = 'f003ffe880d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_video_editor_id', 'editor', ['editor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_constraint('fk_video_editor_id', type_='foreignkey')
        batch_op.drop_column('editor_id')

    # ### end Alembic commands ###
