"""Add chapter column to Editorhandoff

Revision ID: 35f7d58d9974
Revises: 2344cb22888f
Create Date: 2025-04-24 23:55:48.323989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f7d58d9974'
down_revision = '2344cb22888f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editor_handoff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter', sa.String(length=200), nullable=True))
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('progress',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editor_handoff', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('chapter')

    # ### end Alembic commands ###
