"""Add Editor model

Revision ID: 940e0c6a6b90
Revises: b69d8ceab401
Create Date: 2025-04-22 23:54:41.007481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940e0c6a6b90'
down_revision = 'b69d8ceab401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
