"""Add unique constraint to comment log file path

Revision ID: ce5d39d4738f
Revises: 7bb7bb7767e1
Create Date: 2025-06-26 19:40:36.178173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce5d39d4738f'
down_revision = '7bb7bb7767e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher')
    op.drop_table('formatted_supervisor_schedule')
    with op.batch_alter_table('editor_handoff', schema=None) as batch_op:
        batch_op.alter_column('editor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('review_comments_log', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['docx_file_path'])

    with op.batch_alter_table('source_material', schema=None) as batch_op:
        batch_op.drop_constraint('fk_source_supervisor', type_='foreignkey')
        batch_op.create_foreign_key(None, 'supervisor', ['supervisor_id'], ['id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'supervisor', ['supervisor_id'], ['id'])

    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teacher', type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_teacher', 'teacher', ['teacher_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))

    with op.batch_alter_table('supervisor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('source_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_source_supervisor', 'supervisor', ['supervisor_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('review_comments_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('editor_handoff', schema=None) as batch_op:
        batch_op.alter_column('editor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('formatted_supervisor_schedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('time_range', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['supervisor_id'], ['supervisor.id'], name='formatted_supervisor_schedule_supervisor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='formatted_supervisor_schedule_pkey')
    )
    op.create_table('teacher',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='teacher_pkey')
    )
    # ### end Alembic commands ###
